# Postgres config setup — sourced by install.sh, not run standalone.
#
# Relies on these being defined by install.sh before sourcing:
#   vars:  OS, CONFIGS_DIR, LOCAL_DIR
#   funcs: info, warn, copy_template
#
# macOS + Homebrew only. Each installed PostgreSQL version's real config lives in
# its data dir and is generated by initdb, so instead of rewriting it we append a
# managed include block. PostgreSQL uses last-assignment-wins, so the includes
# (repo-wide overrides → machine-local) override the initdb defaults above while
# leaving that base untouched for clean upgrades. Installed versions are
# discovered dynamically from `brew list`, so adding/removing a postgresql@N
# formula needs no change here.

setup_postgres() {
  [ "$OS" = "macos" ] || return 0
  [ -f "$CONFIGS_DIR/postgres/overrides.conf" ] || return 0

  copy_template "postgres.conf"

  if ! command -v brew >/dev/null 2>&1; then
    warn "Homebrew not found, skipping Postgres config"
    return 0
  fi

  local brew_prefix local_conf block_start block_end versions
  brew_prefix="$(brew --prefix)"
  local_conf="$LOCAL_DIR/postgres.conf"
  block_start="# >>> configs-managed (postgres overrides) >>>"
  block_end="# <<< configs-managed (postgres overrides) <<<"

  # Discover installed PostgreSQL formulae dynamically (postgresql@14, @15, …).
  versions="$(brew list --formula 2>/dev/null | grep -E '^postgresql@[0-9.]+$' || true)"
  if [ -z "$versions" ]; then
    warn "No PostgreSQL versions installed. Run 'brew bundle install --file=$CONFIGS_DIR/Brewfile' and rerun ./install.sh."
    return 0
  fi

  local formula conf tmp found_any=false
  while IFS= read -r formula; do
    [ -n "$formula" ] || continue
    conf="$brew_prefix/var/$formula/postgresql.conf"
    if [ ! -f "$conf" ]; then
      warn "$formula installed but $conf not found (not initdb'd yet?), skipping"
      continue
    fi
    found_any=true

    # Strip any previous managed block so this stays idempotent.
    if grep -qF "$block_start" "$conf"; then
      tmp="$(mktemp)"
      sed '/^# >>> configs-managed (postgres overrides) >>>$/,/^# <<< configs-managed (postgres overrides) <<<$/d' "$conf" > "$tmp"
      cat "$tmp" > "$conf"
      rm -f "$tmp"
    fi

    info "Appending managed Postgres overrides to $conf"
    cat >> "$conf" <<EOF

$block_start
# Layer order (PostgreSQL: last assignment wins):
#   1. initdb base config above
#   2. Repo-wide overrides:        $CONFIGS_DIR/postgres/overrides.conf
#   3. Machine-specific overrides: $local_conf
# Edit those source files and rerun install.sh; do not edit between these markers.
include_if_exists '$CONFIGS_DIR/postgres/overrides.conf'
include_if_exists '$local_conf'
$block_end
EOF
  done <<< "$versions"

  if [ "$found_any" = true ]; then
    warn "Postgres config changed — restart running instances to apply, e.g.: brew services restart $(head -1 <<< "$versions")"
  fi
}

setup_postgres
